CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pg_trgm;


CREATE SCHEMA IF NOT EXISTS competitor;
GRANT ALL PRIVILEGES ON SCHEMA competitor TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA competitor
  GRANT ALL ON TABLES TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA competitor
  GRANT ALL ON SEQUENCES TO app;