GET http://localhost:8083/oauth/instagram/authorize?userId=12345 HTTP/1.1
Host: localhost:8083
User-Agent: PostmanRuntime/7.29.0
Accept: */*
Accept-Encoding: gzip, deflate, br
Connection: keep-alive  

###
POST https://erupt-relenting-detoxify.ngrok-free.dev/debug/collect/own/27157438937198248 HTTP/1.1
Host: erupt-relenting-detoxify.ngrok-free.dev
Content-Type: application/json
User-Agent: Java/17.0.2
Accept: */*

###
POST https://erupt-relenting-detoxify.ngrok-free.dev/debug/collect/own/17841441888584276 HTTP/1.1
Host: erupt-relenting-detoxify.ngrok-free.dev
Content-Type: application/json
User-Agent: Java/17.0.2
Accept: */*

###
GET https://erupt-relenting-detoxify.ngrok-free.dev/debug/hashtag/sesjebuduarowe?ownerIgId=17841441888584276 HTTP/1.1 

###
GET https://erupt-relenting-detoxify.ngrok-free.dev/debug/hashtag/sesjebuduarowe/top-media?ownerIgId=    HTTP/1.1

###
GET http://localhost:8083/debug/hashtag/fotografiabuduarowa/top-media?ownerIgId=17841441888584276 HTTP/1.1

###
GET http://erupt-relenting-detoxify.ngrok-free.dev/actuator/health HTTP/1.1

###
POST http://localhost:8083/debug/monitored-profiles?ownerIgId=17841441888584276&competitorHandle=sasserstillsboudoir HTTP/1.1

###
GET http://localhost:8083/debug/monitored-profiles/17841441888584276 HTTP/1.1

###
GET http://localhost:8083/actuator/mappings HTTP/1.1

###
POST http://localhost:8083/collect/competitor HTTP/1.1
Content-Type: application/json

{
    "competitorUsername": "sasserstillsboudoir",
    "platform": "INSTAGRAM"
}

###
POST http://localhost:8083/debug/monitored-hashtag
Content-Type: application/json

{
    "ownerIgId": 17841441888584276,
    "hashtag": "sesjebuduarowe"
}

###
POST http://localhost:8083/collect/hashtag HTTP/1.1
Content-Type: application/json

{
    "platform": "INSTAGRAM",
    "hashtag": "sesjebuduarowe"
}